#!/usr/bin/env bash
# This is a script that handle cleanup and termination
pid_file="/var/run/myscript.pid"
cleanup_and_exit() {
    echo "Cleaning up and exiting..."
    rm -f "$pid_file"
    exit 0
}
handle_sigterm() {
    echo "I hate the kill command"
}
handle_sigint() {
    echo "Y U no love me?!"
}
trap cleanup_and_exit SIGQUIT SIGTERM
trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
echo $$ > "$pid_file"
echo "PID file created: $pid_file"
echo "To infinity and beyond..."
while true; do
    sleep 1
done
