#!/usr/bin/env bash
# Function to check if the process is running
case "$1" in
    start)
        ./manage_my_process start
        ;;

    stop)
        ./manage_my_process stop
        ;;

    restart)
        ./manage_my_process restart
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
