#!/usr/bin/env bash
#Find and stop the 4-to_infinity_and_beyond process using kill
process_name="4-to_infinity_and_beyond"
pid=$(pgrep -f "$process_name")
if [ -n "$pid" ]; then 
    kill "$pid"
else
    echo "Process with name '$process_name' not found."
fi
